name: Patch Boot with KernelSU
on:
  workflow_dispatch:
    inputs:
      device:
        required: true
        default: "myphone"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout KernelSU
        uses: actions/checkout@v4
        with:
          repository: tiann/KernelSU
          ref: main

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Download boot.img
        run: wget -O boot.img "https://files.catbox.moe/tynfs3.img"

      - name: Build ksud
        run: |
          cd userspace
          go build -o ksud ./cmd/ksud
          mv ksud ..

      - name: Patch boot.img
        run: ./ksud patch bootimg boot.img -o ksu_${{ inputs.device }}.img

      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: ksu_patched_boot
          path: ksu_*.img
